name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:
  push:
    branches:
      - main  # Or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: yourusername/personal-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push to the forked repository
        run: |
          git remote set-url origin https://github.com/organizationname/org-repo.git
          git push --force --all origin
